### ISSUE TITLE
Color Value must be numbers, comment after color code

### ISSUE THREAD

**Issue by Shiningingy** [thmsndk/vscode.poe2-filter#3]
It gives "Color Value must be numbers" error when using a comment after colour code like "SetTextColor 255 0 0 # T1 white"

**Comment by thmsndk** [comment]
@Shiningingy Thank you for reporting it!
I'm gonna be out of the house for most of the day, but I will fix it as soon as I'm able to

**Comment by thmsndk** [comment]
This issue should now be fixed in the release I just pushed
